### ISSUE TITLE
Disparité entre preview quiz et affichage quiz

### ISSUE THREAD

**Issue by louis-antoine-etsmtl** [louis-antoine-etsmtl/EvalueTonSavoir#32]
From ETS-PFE042-EvalueTonSavoir-Frontend created by [louis-antoine-etsmtl](https://github.com/louis-antoine-etsmtl): louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend#25  

**Describe the bug**
Geneviève: Bonjour. J'ai remarqué que l'affichage des équations entre $$ $$ n'apparaît pas de la même façon dans l'aperçu et dans le navigateur une fois le quiz lancé: elles sont centrées dans l'aperçu et pas dans le vrai quiz.

**Screenshots**
![f27febc1-acc8-4442-960c-ccd3bbdbb039](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/61054719/a25cc1b1-0dcb-4e24-b795-8e62520f6bfd)
![dce58e5c-ce69-435e-84e0-7d97e7f0962e](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/61054719/e2f155ac-7ac9-4c8b-af89-20b352afddaf)
![554fe435-2fab-47e7-8283-371a9e8969c7](https://github.com/louis-antoine-etsmtl/ETS-PFE042-EvalueTonSavoir-Frontend/assets/61054719/0ce41ce9-8a60-49a5-a838-14ae8ef41002)

**Comment by louis-antoine-etsmtl** [comment]
Exemple de code pour reproduire: 
[13:03] Savard, Geneviève
::Question numérique avec réponse exacte::

$$ 1+8 $$  {#=9}
 
::Aire:: 

Illustrez clairement la région délimitée par les courbes $$ y\= -2x^2+1.5$$ et $$y \= \sin (2x-0.5)$$ dans une fenêtre appropriée.  Donnez son aire arrondie à la deuxième décimale, en utilisant le point décimal. 

{#=2.3755:0.01 

#### $$ \int\limits_\{-1,01741\}^\{0,63435\} \left( \left( -2x^2+1,5

\right)-\left( \sin (2x-0,5 \right) \right) \,dx  

   \approx     2,3755  $$ }

**Comment by fuhrmanator** [comment]
Une solution, selon moi, serait d'utiliser à 100% un parseur de GIFT ainsi que le plugiciel [KaTeX](https://katex.org/). C'est ce que je fais avec mon éditeur à https://github.com/fuhrmanator/GIFT-grammar-PEG.js/blob/fb0bb5f38f0077c0e7667aa9ebe68b520316fdfc/docs/editor/editor.html#L27-L49

Ça veut dire que vos pages pour éditer et pour afficher doivent utiliser le même code pour afficher autant possible.

**Comment by fuhrmanator** [comment]
Voici un exemple avec mon éditeur pour supporter du LaTeX dans le texte (même ligne) et séparé (ligne séparée): 
https://fuhrmanator.github.io/GIFT-grammar-PEG.js/editor/editor.html?text=2onDBIx9pCzJI2nBJLPGyKaCIOrGKIWkBLB8ILJ8oKpFIzMhhkNYGbC6LGTKU7XbGMBHuPMfUWhLjG00

C'est KaTeX qui fait tout dans son plug-in.

**Comment by fuhrmanator** [comment]
Cette page est possiblement utile pour supporter KaTeX dans react native - https://medium.com/@flankstaek/displaying-katex-in-react-native-9655c2628a7d

**Comment by fuhrmanator** [comment]
Il y a des différences entre la page éditeur https://github.com/louis-antoine-etsmtl/EvalueTonSavoir/blob/main/client/src/components/Editor/Editor.tsx et une page d'affichage de question pour un quiz p.ex. https://github.com/louis-antoine-etsmtl/EvalueTonSavoir/blob/main/client/src/components/Questions/TrueFalseQuestion/TrueFalseQuestion.tsx

Je ne vois pas tout de suite exactement comment katex est activé dans les deux cas (l'affichage pour TrueFalseQuestion met une balise <Latex> mais l'éditeur ne le fait pas (au moins pas directement). Si @valkyrie1  peut trouver plus d'infos avant, on va avoir une rencontre plus productive.

**Comment by valkyrie1** [comment]
Modifications faites pour que le rendu de l'affichage des quizs utilise le même module que l'édition. On utilise le format de mise en page de la classe TextType.ts. Ajout de l'utilisation des formules sur la même ligne.

**Comment by fuhrmanator** [comment]
Bonjour - je crois que ce bogue n'est pas Closed réellement à cause de la https://github.com/louis-antoine-etsmtl/EvalueTonSavoir/pull/63
